on: [push, pull_request]

name: Continuous Integration

env: 
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.6.2
  SLQLX_FEATURES: "rustls,postgres"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Check
        run: cargo check
  
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run rustfmt
        run: cargo fmt -- --check
    
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --all-targets --release --all-features --verbose
      - name: Test
        run: cargo test --verbose
      - name: Install Tarpaulin (Code coverage)
        run: cargo install cargo-tarpaulin
      - name: Generate Coverage
        run: cargo tarpaulin

